export const BASE_URL = 'https://api.github.com';

export const FAVOURITES_STORAGE_KEY = 'REACT_TEST_FAVOURITES_STORAGE_KEY';
export const FAVOURITES_SET_STATUS = 'FAVOURITES_SET_STATUS';

export const GET_REPO_LIST_REQUEST = 'GET_REPO_LIST_REQUEST';
export const GET_REPO_LIST_SUCCESS = 'GET_REPO_LIST_SUCCESS';
export const GET_REPO_LIST_FAIL = 'GET_REPO_LIST_FAIL';

export const GET_CONTRIBUTORS_LIST_REQUEST = 'GET_CONTRIBUTORS_LIST_REQUEST';
export const GET_CONTRIBUTORS_LIST_SUCCESS = 'GET_CONTRIBUTORS_LIST_SUCCESS';
export const GET_CONTRIBUTORS_LIST_FAIL = 'GET_CONTRIBUTORS_LIST_FAIL';
